### ISSUE TITLE
agico problem

### ISSUE THREAD

**Issue by lihaooo** [gethugothemes/documentation#31]
Start building sites …
Built in 74 ms
Error: Error building site: TOCSS: failed to transform "style.scss" (text/x-scss): SCSS processing failed: file "/Users/admin/workspace/sysfun/themes/agico-hugo/assets/scss/_typography.scss", line 3, col 18: Undefined variable: "$secondary-font".

---

hugo v0.83.1-5AFE0A57+extended darwin/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio

---

it seems that we are missing the [variables] section in params.toml, so that the scss transformation failed
@davidsneighbour I bought agico theme from themefisher, but the doc is only displayed on this repo. I may need your help, thx a lot.

**Comment by lihaooo** [comment]
it seems that we are missing the [variables] section in params.toml, so that the scss transformation failed
@davidsneighbour may need your help, thx a lot

**Comment by davidsneighbour** [comment]
Did you run `npm install` before running Hugo? It looks like Hugo pipes can't find the bootstrap libraries. I'll try to replicate the issue.

**Comment by lihaooo** [comment]
There is no `package.json` in the zip package downloaded from themefisher.

**Comment by davidsneighbour** [comment]
Right, Bootstrap is included via stylesheets.

I can run Hugo on the exampleSite setup without issues. Let's see what is changed between the samples and your site. Please post your config.toml (without languages part) and what changes you did to the stylesheets up to now. 

Also if the messages on the CLI show more info before that error - let's post that too. If Hugo would have a bigger issue with SCSS the error message would look different. Right now we have to assume, that it can't find the `_variables.scss` file somehow.

`$secondary-font` is defined in `assets/scss/_variables.scss` that is loaded by `style.scss` before `_typography.scss` is loaded, so it should work if nothing is changed on that setup. 

If you can give me access to your repo (no need to make it public, just add @davidsneighbour if required) I can have a look at it if these points before don't help.

**Comment by davidsneighbour** [comment]
Hi again, I re-downloaded the theme files and am experiencing the same issues as you now. It appears the config.toml file was not updated in that package. I'll get a solution as soon as possible. Ignore my previous message.

As far as I see you need the following in your config.toml with values (there are no default values):

```
[params.variables]
primary_color=""
secondary_color=""
bg_secondary=""
text_dark=""
text_light=""
text_color=""
border_color=""
bg_gradient_primary=""
bg_gradient_secondary=""
btn_gradient_primary=""
black=""
white=""
gray=""
primary_font=""
primary_font_type=""
secondary_font=""
secondary_font_type=""
icon_font=""
```

**Comment by lihaooo** [comment]
Thanks a lot. Actually, I have found the same point also, and add the variables to make it work first, then tried to ask for your help. Since I didn't know what is the correct values of the variables according to the theme.

**Comment by Mykolaichenko** [comment]
After adding fix I have: 
`Error: Error building site: TOCSS: failed to transform "style.scss" (text/x-scss): SCSS processing failed: file "stdin", line 3, col 15: Invalid CSS after "$primary-color:": expected expression (e.g. 1px, bold), was ";" 
`

**Comment by somratpro** [comment]
Hello @Mykolaichenko 

Sorry for our delay. we fixed that issue, now you can download the latest file and run it.
